language: python
python:
  - "3.6"

services:
  - docker

before_scripts: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  # - docker-compose run app sh -c "python manage.py runserver"

# deploy:
#   provider: heroku
#   api_key:
#     secure: "768d3784-3882-494f-9d61-d58bbfc6bd22"
#   app: "favrecipe-be"
#   on:
#     branch: main