language: python
python:
  - "3.6"

services:
  - docker

before_install:
    # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

before_scripts: pip install docker-compose

script:
  # - docker-compose run app sh -c "while !</dev/tcp/db/5432; do sleep 1; done;"
  # - docker-compose run app sh -c "python manage.py test && flake8"
  - docker-compose run app sh -c "while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000"
