language: python
python:
- '3.6'
services:
- docker
before_scripts: pip install docker-compose
script:
- docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: SKz6QsE6L5EJ4i9L1H+03qNouvc5ZRfj/5a8EqZ/gfvySqdJokffgiGHFwmz5VEoDGu9uBQ9RZdVpjnbJpk5FSExSV9zpDdJFENYmsf7AjQ3ysl+WAQBv6cmdxed6xylbV001vxFY9FPulbyO963JpSgxG6Re9Ed13cIa0rOJ7qULhfuJsXpAhYAkqcAEGkTkxEuWLkQE2BHRMUqUGAfCyjcJVm0qKd4Jniw21yURBnWO596BbyPRZpyWyiipgFxXP5P1uvZOJ8wuvkLiW99m48QuoZs1zFozOaFsshmFf7TcoznKy1/1tHEqZBQOxFma4zFphCbL9cBFfUmn+oxDv6Q69RH/PJQO7Jo86Eugxd7YKmzP1RWeiEFYyHrceDPAcRWeMQ3R1hnTPL3zxGZzaWCyXkerVpmv/6Rthx/YK54ufHYq6SN1hi4T/qpOVHr9QlPcpgieIt0PuX95hX9bjA8BJHUsXRTkVzsRa5c3rEXETZGGeNbymb3asEWolBIfIYg3+mLRiGOCg4cbYGlBbq21dSw6Q9XLVH8tAZRh+Up858itAgy0uB338RNszhPlS5E6q/+KjjKa/E7YsGXxv3wBMSvdtRWvUMldQKiZns3qBx0lUZ30WlZEiwMoZhqCgwzW0sxlk8kyWOUFd1yLCstTy1mekiV8OhD8OX+oC0=
